apiVersion: v1
kind: Service
metadata:
  name: foyer-app
spec:
  type: NodePort
  selector:
    app: foyer-app
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 30036

