apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdA==      # base64 of 'root'
  mysql-database: Zm95ZXJfZGI=         # base64('foyer_db')
  mysql-user: dHBwcm9qZXQ=             # base64('tpprojet')
  mysql-password: dHBwcm9qZXQ=         # base64('tpprojet')